#version 460
layout(local_size_x = 64) in;

// a[i] += scale * b[i]
layout(set = 0, binding = 0) buffer Accum { float a[]; };
layout(set = 0, binding = 1) readonly buffer Src { float b[]; };

layout(push_constant) uniform PC {
    uint N;
    uint scale_bits; // float reinterpreted as uint
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i < N) {
        float scale = uintBitsToFloat(scale_bits);
        a[i] += scale * b[i];
    }
}
